### ISSUE TITLE
报错，无法解决，严格按照教程

### ISSUE THREAD

**Issue by mitokohaku** [Samuel-0-0/phicomm_dc1-esphome#29]
[32mINFO Reading configuration dc1.yaml...[0m
[33mWARNING ESP8266: Pin 6 (6-11) might already be used by the flash interface. Be warned.[0m
[33mWARNING ESP8266: Pin 7 (6-11) might already be used by the flash interface. Be warned.[0m
Failed config

cat9554: [source dc1.yaml:88]

  Component not found: cat9554.
  id: cat9554_hub
  irq_pin: GPIO4
binary_sensor.gpio: [source dc1.yaml:130]
  platform: gpio
  name: phicomm_dc1_api key1
  internal: True
  pin:  [source dc1.yaml:136]

    [cat9554] is an invalid option for [pin]. Please check the indentation.
    cat9554: cat9554_hub [source dc1.yaml:136]
    number: 0
    mode: INPUT
  filters:
    - invert: {}
    - delayed_on: 50ms
    - delayed_off: 50ms
  on_click:
    - min_length: 50ms
      max_length: 500ms
      then:
        - switch.toggle: switch1
binary_sensor.gpio: [source dc1.yaml:149]
  platform: gpio
  name: phicomm_dc1_api key2
  internal: True
  pin:  [source dc1.yaml:155]

    [cat9554] is an invalid option for [pin]. Please check the indentation.
    cat9554: cat9554_hub [source dc1.yaml:155]
    number: 1
    mode: INPUT
  filters:
    - invert: {}
    - delayed_on: 50ms
    - delayed_off: 50ms
  on_click:
    - min_length: 50ms
      max_length: 500ms
      then:
        - switch.toggle: switch2
binary_sensor.gpio: [source dc1.yaml:168]
  platform: gpio
  name: phicomm_dc1_api key3
  internal: True
  pin:  [source dc1.yaml:174]

    [cat9554] is an invalid option for [pin]. Please check the indentation.
    cat9554: cat9554_hub [source dc1.yaml:174]
    number: 2
    mode: INPUT
  filters:
    - invert: {}
    - delayed_on: 50ms
    - delayed_off: 50ms
  on_click:
    - min_length: 50ms
      max_length: 500ms
      then:
        - switch.toggle: switch3
output.gpio: [source dc1.yaml:241]
  platform: gpio
  id: realy3
  setup_priority: 900
  pin:  [source dc1.yaml:247]

    [cat9554] is an invalid option for [pin]. Please check the indentation.
    cat9554: cat9554_hub [source dc1.yaml:247]
    number: 4
    mode: OUTPUT
    inverted: False
output.gpio: [source dc1.yaml:252]
  platform: gpio
  id: realy2
  setup_priority: 900
  pin:  [source dc1.yaml:257]

    [cat9554] is an invalid option for [pin]. Please check the indentation.
    cat9554: cat9554_hub [source dc1.yaml:257]
    number: 5
    mode: OUTPUT
    inverted: False
output.gpio: [source dc1.yaml:262]
  platform: gpio
  id: realy1
  setup_priority: 900
  pin:  [source dc1.yaml:267]

    [cat9554] is an invalid option for [pin]. Please check the indentation.
    cat9554: cat9554_hub [source dc1.yaml:267]
    number: 6
    mode: OUTPUT
    inverted: False
output.gpio: [source dc1.yaml:272]
  platform: gpio
  id: realy0
  setup_priority: 900
  pin:  [source dc1.yaml:277]

    [cat9554] is an invalid option for [pin]. Please check the indentation.
    cat9554: cat9554_hub [source dc1.yaml:277]
    number: 7
    mode: OUTPUT
    inverted: False

**Comment by jyz0501** [comment]
我在HASSIO的ESPHOME web端 打算生成编译文件，也是提示cat9554 硬件的文件不正确，尝试把文件夹拷贝到.esphome 目录下不管用，请问应该怎么放置

**Comment by zsd410** [comment]
应该是cat9554的那个部分没搞好吧

**Comment by ganlin12334** [comment]
我也是这个问题，请问兄弟解决了没？

**Comment by ganlin12334** [comment]
加了自定义组件
external_components:
  - source: components
  
解决了这个问题，但是新的问题又来了…………

  - Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 825, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 803, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
  File "/esphome/esphome/config.py", line 974, in read_config
    res = load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 829, in load_config
    return _load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 817, in _load_config
    result = validate_config(config, command_line_substitutions)
  File "/esphome/esphome/config.py", line 744, in validate_config
    result.run_validation_steps()
  File "/esphome/esphome/config.py", line 124, in run_validation_steps
    task.step.run(self)
  File "/esphome/esphome/config.py", line 488, in run
    validated = schema(input_conf)
  File "/esphome/esphome/voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/esphome/esphome/voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/esphome/esphome/voluptuous_schema.py", line 148, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/esphome/esphome/pins.py", line 66, in validator
    return entry[1](value)
TypeError: 'tuple' object is not callable
